version: '1'
services:
  melita_io_batch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: melita_io_batch
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
