version: '1'
services:
  melita-io-batch:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: melita-io-batch
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
      EGRESS_URL: 
      EXECUTE_SINGLE_COMMAND: no
      SINGLE_COMMAND: addDownlinkDeviceQueue
      AUTHENTICATION_API_KEY: xxxxxxxxx
      ERROR_URL: env('ERROR_URL', ''),
      MELITA_API_URL: https://www.melita.io/api/iot-gateway
      DEVICE_EUI_LIST: 70B3D52DD3003E30,70B3D52DD3003E30
