version: "3.0"
services:
  melita-io-batch:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "Melita IO Batch"
      MODULE_TYPE: "Output"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      PROFILE_IDS: ''
      MATCHED_URL: ''
    ports:
      - 80:80